// Generated by islamic_kit_plus tool/generate_native_data.dart — DO NOT EDIT.
// Regenerate from the Dart package; every literal here mirrors the Dart source.

package io.github.bilalelsayed97.islamickit.domain.enums

import io.github.bilalelsayed97.islamickit.domain.valueobjects.Coordinates
import io.github.bilalelsayed97.islamickit.domain.valueobjects.MethodAdjustments
import io.github.bilalelsayed97.islamickit.domain.valueobjects.MethodParams

/**
 * A prayer-time calculation method (twilight authority).
 *
 * Each method carries its numeric [id] and short [code], a human-readable
 * [methodName], and its strongly-typed [params]. Methods with ids 1–23 keep the
 * numbering of the aladhan API; the regional authorities aladhan does not
 * publish are numbered from 101 so the two id spaces never collide. Entries are
 * declared in the Dart package's order, so [entries] matches
 * `CalculationMethod.values`.
 */
enum class CalculationMethod(
    /** Numeric id (aladhan id for ids <= 99). */
    val id: Int,
    /** Short upper-case code, e.g. `"MWL"`. */
    val code: String,
    /** Human-readable authority name. */
    val methodName: String,
    /** The method's twilight parameters and published corrections. */
    val params: MethodParams,
    /** Whether Fajr/Isha are bounded by the Moonsighting Committee twilight. */
    val usesMoonsighting: Boolean = false,
) : Localized {
    KARACHI(
        1,
        "KARACHI",
        "University of Islamic Sciences, Karachi",
        MethodParams(fajrAngle = 18.0, ishaAngle = 18.0, adjustments = MethodAdjustments(dhuhr = 1), location = Coordinates(24.8614622, 67.0099388)),
    ),
    ISNA(
        2,
        "ISNA",
        "Islamic Society of North America (ISNA)",
        MethodParams(fajrAngle = 15.0, ishaAngle = 15.0, adjustments = MethodAdjustments(dhuhr = 1), location = Coordinates(39.70421229999999, -86.39943869999999)),
    ),
    MWL(
        3,
        "MWL",
        "Muslim World League",
        MethodParams(fajrAngle = 18.0, ishaAngle = 17.0, adjustments = MethodAdjustments(dhuhr = 1), location = Coordinates(51.5194682, -0.1360365)),
    ),
    MAKKAH(
        4,
        "MAKKAH",
        "Umm Al-Qura University, Makkah",
        MethodParams(fajrAngle = 18.5, ishaMinutesAfterMaghrib = 90, ramadanIshaMinutesAfterMaghrib = 120, location = Coordinates(21.3890824, 39.8579118)),
    ),
    EGYPT(
        5,
        "EGYPT",
        "Egyptian General Authority of Survey",
        MethodParams(fajrAngle = 19.5, ishaAngle = 17.5, adjustments = MethodAdjustments(dhuhr = 1), location = Coordinates(30.0444196, 31.2357116)),
    ),
    TEHRAN(
        7,
        "TEHRAN",
        "Institute of Geophysics, University of Tehran",
        MethodParams(fajrAngle = 17.7, ishaAngle = 14.0, maghribAngle = 4.5, midnightMode = MidnightMode.JAFARI, location = Coordinates(35.6891975, 51.3889736)),
    ),
    GULF(
        8,
        "GULF",
        "Gulf Region",
        MethodParams(fajrAngle = 19.5, ishaMinutesAfterMaghrib = 90, location = Coordinates(24.1323638, 53.3199527)),
    ),
    KUWAIT(
        9,
        "KUWAIT",
        "Kuwait",
        MethodParams(fajrAngle = 18.0, ishaAngle = 17.5, location = Coordinates(29.375859, 47.9774052)),
    ),
    QATAR(
        10,
        "QATAR",
        "Qatar",
        MethodParams(fajrAngle = 18.0, ishaMinutesAfterMaghrib = 90, location = Coordinates(25.2854473, 51.5310398)),
    ),
    SINGAPORE(
        11,
        "SINGAPORE",
        "Majlis Ugama Islam Singapura, Singapore",
        MethodParams(fajrAngle = 20.0, ishaAngle = 18.0, adjustments = MethodAdjustments(dhuhr = 1), location = Coordinates(1.352083, 103.819836)),
    ),
    FRANCE(
        12,
        "FRANCE",
        "Union Organization Islamic de France",
        MethodParams(fajrAngle = 12.0, ishaAngle = 12.0, location = Coordinates(48.856614, 2.3522219)),
    ),
    TURKEY(
        13,
        "TURKEY",
        "Diyanet İşleri Başkanlığı, Turkey",
        MethodParams(fajrAngle = 18.0, ishaAngle = 17.0, location = Coordinates(39.9333635, 32.8597419)),
    ),
    RUSSIA(
        14,
        "RUSSIA",
        "Spiritual Administration of Muslims of Russia",
        MethodParams(fajrAngle = 16.0, ishaAngle = 15.0, location = Coordinates(54.73479099999999, 55.9578555)),
    ),
    MOONSIGHTING(
        15,
        "MOONSIGHTING",
        "Moonsighting Committee Worldwide (Moonsighting.com)",
        MethodParams(fajrAngle = 18.0, ishaAngle = 18.0, adjustments = MethodAdjustments(dhuhr = 5, maghrib = 3)),
        usesMoonsighting = true,
    ),
    DUBAI(
        16,
        "DUBAI",
        "The Gulf Region — Dubai",
        MethodParams(fajrAngle = 18.2, ishaAngle = 18.2, adjustments = MethodAdjustments(sunrise = -3, dhuhr = 3, asr = 3, maghrib = 3), location = Coordinates(25.0762677, 55.087404)),
    ),
    JAKIM(
        17,
        "JAKIM",
        "Jabatan Kemajuan Islam Malaysia (JAKIM)",
        MethodParams(fajrAngle = 20.0, ishaAngle = 18.0, location = Coordinates(3.139003, 101.686855)),
    ),
    TUNISIA(
        18,
        "TUNISIA",
        "Tunisia",
        MethodParams(fajrAngle = 18.0, ishaAngle = 18.0, location = Coordinates(36.8064948, 10.1815316)),
    ),
    ALGERIA(
        19,
        "ALGERIA",
        "Algeria",
        MethodParams(fajrAngle = 18.0, ishaAngle = 17.0, location = Coordinates(36.753768, 3.0587561)),
    ),
    KEMENAG(
        20,
        "KEMENAG",
        "Kementerian Agama Republik Indonesia",
        MethodParams(fajrAngle = 20.0, ishaAngle = 18.0, location = Coordinates(-6.2087634, 106.845599)),
    ),
    MOROCCO(
        21,
        "MOROCCO",
        "Morocco",
        MethodParams(fajrAngle = 18.0, ishaAngle = 17.0, location = Coordinates(33.9715904, -6.8498129)),
    ),
    PORTUGAL(
        22,
        "PORTUGAL",
        "Comunidade Islamica de Lisboa",
        MethodParams(fajrAngle = 18.0, ishaMinutesAfterMaghrib = 77, maghribMinutesAfterSunset = 3, location = Coordinates(38.7222524, -9.1393366)),
    ),
    JORDAN(
        23,
        "JORDAN",
        "Ministry of Awqaf, Islamic Affairs and Holy Places, Jordan",
        MethodParams(fajrAngle = 18.5, ishaMinutesAfterMaghrib = 90, location = Coordinates(31.9461222, 35.923844)),
    ),
    OMAN(
        101,
        "OMAN",
        "Ministry of Endowments and Religious Affairs, Oman",
        MethodParams(fajrAngle = 18.5, ishaMinutesAfterMaghrib = 90, location = Coordinates(23.588, 58.3829)),
    ),
    MUNICH(
        102,
        "MUNICH",
        "Islamic Center of Munich, Germany",
        MethodParams(fajrAngle = 18.0, ishaAngle = 17.0, location = Coordinates(48.1351, 11.582)),
    ),
    MALDIVES(
        103,
        "MALDIVES",
        "Ministry of Islamic Affairs, Maldives",
        MethodParams(fajrAngle = 18.0, ishaAngle = 17.0, location = Coordinates(4.1755, 73.5093)),
    ),
    CANADA(
        104,
        "CANADA",
        "Canada",
        MethodParams(fajrAngle = 15.0, ishaAngle = 15.0, location = Coordinates(45.4215, -75.6972)),
    ),
    TAJIKISTAN(
        105,
        "TAJIKISTAN",
        "Islamic Center of Tajikistan",
        MethodParams(fajrAngle = 18.0, ishaAngle = 17.0, location = Coordinates(38.5598, 68.787)),
    ),
    VIENNA(
        106,
        "VIENNA",
        "Islamic Community of Austria, Vienna",
        MethodParams(fajrAngle = 18.0, ishaAngle = 17.0, location = Coordinates(48.2082, 16.3738)),
    ),
    BELGIUM(
        107,
        "BELGIUM",
        "Belgium",
        MethodParams(fajrAngle = 18.0, ishaAngle = 17.0, location = Coordinates(50.8503, 4.3517)),
    ),
    SUDAN(
        108,
        "SUDAN",
        "Sudan",
        MethodParams(fajrAngle = 19.5, ishaAngle = 17.5, location = Coordinates(15.5007, 32.5599)),
    ),
    LIBYA(
        109,
        "LIBYA",
        "Libya",
        MethodParams(fajrAngle = 19.5, ishaAngle = 17.5, location = Coordinates(32.8872, 13.1913)),
    ),
    IRAQ(
        110,
        "IRAQ",
        "Iraq",
        MethodParams(fajrAngle = 18.0, ishaAngle = 17.0, location = Coordinates(33.3152, 44.3661)),
    ),
    LUXEMBOURG(
        111,
        "LUXEMBOURG",
        "Luxembourg",
        MethodParams(fajrAngle = 18.0, ishaAngle = 17.0, location = Coordinates(49.6116, 6.1319)),
    ),
    CUSTOM(
        99,
        "CUSTOM",
        "Custom",
        MethodParams(fajrAngle = 15.0, ishaAngle = 15.0),
    );

    /** Whether [id] is an aladhan method id (ids above 99 are package extensions). */
    val isAladhanMethod: Boolean
        get() = id <= 99

    override fun title(language: Language): String = when (this) {
        KARACHI -> if (language == Language.AR) "كراتشي" else "Karachi"
        ISNA -> if (language == Language.AR) "الجمعية الإسلامية لأمريكا الشمالية" else "ISNA"
        MWL -> if (language == Language.AR) "رابطة العالم الإسلامي" else "Muslim World League"
        MAKKAH -> if (language == Language.AR) "أم القرى" else "Umm al-Qura"
        EGYPT -> if (language == Language.AR) "مصر" else "Egypt"
        TEHRAN -> if (language == Language.AR) "طهران" else "Tehran"
        GULF -> if (language == Language.AR) "منطقة الخليج" else "Gulf Region"
        KUWAIT -> if (language == Language.AR) "الكويت" else "Kuwait"
        QATAR -> if (language == Language.AR) "قطر" else "Qatar"
        SINGAPORE -> if (language == Language.AR) "سنغافورة" else "Singapore (MUIS)"
        FRANCE -> if (language == Language.AR) "فرنسا" else "France (UOIF)"
        TURKEY -> if (language == Language.AR) "تركيا (ديانت)" else "Turkey (Diyanet)"
        RUSSIA -> if (language == Language.AR) "روسيا" else "Russia"
        MOONSIGHTING -> if (language == Language.AR) "لجنة رؤية الهلال" else "Moonsighting Committee"
        DUBAI -> if (language == Language.AR) "دبي" else "Dubai"
        JAKIM -> if (language == Language.AR) "ماليزيا (جاكيم)" else "Malaysia (JAKIM)"
        TUNISIA -> if (language == Language.AR) "تونس" else "Tunisia"
        ALGERIA -> if (language == Language.AR) "الجزائر" else "Algeria"
        KEMENAG -> if (language == Language.AR) "إندونيسيا (كيمناغ)" else "Indonesia (Kemenag)"
        MOROCCO -> if (language == Language.AR) "المغرب" else "Morocco"
        PORTUGAL -> if (language == Language.AR) "البرتغال" else "Portugal"
        JORDAN -> if (language == Language.AR) "الأردن" else "Jordan"
        OMAN -> if (language == Language.AR) "عُمان" else "Oman"
        MUNICH -> if (language == Language.AR) "ألمانيا (ميونخ)" else "Germany (Munich)"
        MALDIVES -> if (language == Language.AR) "المالديف" else "Maldives"
        CANADA -> if (language == Language.AR) "كندا" else "Canada"
        TAJIKISTAN -> if (language == Language.AR) "طاجيكستان" else "Tajikistan"
        VIENNA -> if (language == Language.AR) "النمسا (فيينا)" else "Austria (Vienna)"
        BELGIUM -> if (language == Language.AR) "بلجيكا" else "Belgium"
        SUDAN -> if (language == Language.AR) "السودان" else "Sudan"
        LIBYA -> if (language == Language.AR) "ليبيا" else "Libya"
        IRAQ -> if (language == Language.AR) "العراق" else "Iraq"
        LUXEMBOURG -> if (language == Language.AR) "لوكسمبورغ" else "Luxembourg"
        CUSTOM -> if (language == Language.AR) "مخصّص" else "Custom"
    }

    override fun description(language: Language): String = when (this) {
        KARACHI -> if (language == Language.AR) "جامعة العلوم الإسلامية بكراتشي — زاوية 18° لكل من الفجر والعشاء." else "University of Islamic Sciences, Karachi — 18° for both Fajr and Isha."
        ISNA -> if (language == Language.AR) "الجمعية الإسلامية لأمريكا الشمالية — زاوية 15° لكل من الفجر والعشاء." else "Islamic Society of North America — 15° for both Fajr and Isha."
        MWL -> if (language == Language.AR) "رابطة العالم الإسلامي — زاوية فجر 18° وعشاء 17°، وهي شائعة في أوروبا وغيرها." else "Muslim World League — 18° Fajr and 17° Isha, widely used across Europe and beyond."
        MAKKAH -> if (language == Language.AR) "جامعة أم القرى بمكة — زاوية فجر 18.5° مع تحديد العشاء بعد 90 دقيقة من المغرب (120 دقيقة في رمضان)." else "Umm Al-Qura University, Makkah — 18.5° Fajr with Isha fixed at 90 minutes after Maghrib (120 minutes during Ramadan)."
        EGYPT -> if (language == Language.AR) "الهيئة المصرية العامة للمساحة — زاوية فجر 19.5° وعشاء 17.5°." else "Egyptian General Authority of Survey — 19.5° Fajr and 17.5° Isha."
        TEHRAN -> if (language == Language.AR) "معهد الجيوفيزياء بجامعة طهران — زاوية فجر 17.7° وعشاء 14° مع زاوية مغرب 4.5°." else "Institute of Geophysics, University of Tehran — 17.7° Fajr and 14° Isha with a 4.5° Maghrib angle."
        GULF -> if (language == Language.AR) "منطقة الخليج — زاوية فجر 19.5° مع تحديد العشاء بعد 90 دقيقة من المغرب." else "Gulf Region — 19.5° Fajr with Isha fixed at 90 minutes after Maghrib."
        KUWAIT -> if (language == Language.AR) "الكويت — زاوية فجر 18° وعشاء 17.5°." else "Kuwait — 18° Fajr and 17.5° Isha."
        QATAR -> if (language == Language.AR) "قطر — زاوية فجر 18° مع تحديد العشاء بعد 90 دقيقة من المغرب." else "Qatar — 18° Fajr with Isha fixed at 90 minutes after Maghrib."
        SINGAPORE -> if (language == Language.AR) "المجلس الإسلامي في سنغافورة — زاوية فجر 20° وعشاء 18°." else "Majlis Ugama Islam Singapura — 20° Fajr and 18° Isha."
        FRANCE -> if (language == Language.AR) "اتحاد المنظمات الإسلامية في فرنسا — زاوية 12° لكل من الفجر والعشاء." else "Union des Organisations Islamiques de France — 12° for both Fajr and Isha."
        TURKEY -> if (language == Language.AR) "رئاسة الشؤون الدينية التركية (ديانت) — زاوية فجر 18° وعشاء 17°." else "Diyanet İşleri Başkanlığı, Turkey — 18° Fajr and 17° Isha."
        RUSSIA -> if (language == Language.AR) "الإدارة الدينية لمسلمي روسيا — زاوية فجر 16° وعشاء 15°." else "Spiritual Administration of Muslims of Russia — 16° Fajr and 15° Isha."
        MOONSIGHTING -> if (language == Language.AR) "لجنة رؤية الهلال العالمية — زاوية 18° للفجر والعشاء مقيّدة بحساب موسمي يتغيّر مع خط العرض والفصل." else "Moonsighting Committee Worldwide — 18° Fajr and Isha bounded by a seasonal calculation that varies with latitude and time of year."
        DUBAI -> if (language == Language.AR) "دبي — زاوية 18.2° لكل من الفجر والعشاء." else "Dubai — 18.2° for both Fajr and Isha."
        JAKIM -> if (language == Language.AR) "دائرة التنمية الإسلامية الماليزية (جاكيم) — زاوية فجر 20° وعشاء 18°." else "Jabatan Kemajuan Islam Malaysia (JAKIM) — 20° Fajr and 18° Isha."
        TUNISIA -> if (language == Language.AR) "تونس — زاوية 18° لكل من الفجر والعشاء." else "Tunisia — 18° for both Fajr and Isha."
        ALGERIA -> if (language == Language.AR) "الجزائر — زاوية فجر 18° وعشاء 17°." else "Algeria — 18° Fajr and 17° Isha."
        KEMENAG -> if (language == Language.AR) "وزارة الشؤون الدينية بجمهورية إندونيسيا — زاوية فجر 20° وعشاء 18°." else "Kementerian Agama Republik Indonesia — 20° Fajr and 18° Isha."
        MOROCCO -> if (language == Language.AR) "المملكة المغربية — زاوية فجر 18° وعشاء 17°." else "Morocco — 18° Fajr and 17° Isha."
        PORTUGAL -> if (language == Language.AR) "الجالية الإسلامية في لشبونة — زاوية فجر 18° مع تحديد العشاء بعد 77 دقيقة من المغرب." else "Comunidade Islâmica de Lisboa — 18° Fajr with Isha fixed at 77 minutes after Maghrib."
        JORDAN -> if (language == Language.AR) "وزارة الأوقاف والشؤون والمقدسات الإسلامية بالأردن — زاوية فجر 18.5° مع تحديد العشاء بعد 90 دقيقة من المغرب." else "Ministry of Awqaf, Islamic Affairs and Holy Places, Jordan — 18.5° Fajr with Isha fixed at 90 minutes after Maghrib."
        OMAN -> if (language == Language.AR) "وزارة الأوقاف والشؤون الدينية بسلطنة عُمان — زاوية فجر 18.5° مع تحديد العشاء بعد 90 دقيقة من المغرب." else "Ministry of Endowments and Religious Affairs, Oman — 18.5° Fajr with Isha fixed at 90 minutes after Maghrib."
        MUNICH -> if (language == Language.AR) "المركز الإسلامي في ميونخ بألمانيا — زاوية فجر 18° وعشاء 17°." else "Islamic Center of Munich, Germany — 18° Fajr and 17° Isha."
        MALDIVES -> if (language == Language.AR) "وزارة الشؤون الإسلامية بجمهورية المالديف — زاوية فجر 18° وعشاء 17°." else "Ministry of Islamic Affairs, Maldives — 18° Fajr and 17° Isha."
        CANADA -> if (language == Language.AR) "كندا — زاوية 15° لكل من الفجر والعشاء." else "Canada — 15° for both Fajr and Isha."
        TAJIKISTAN -> if (language == Language.AR) "المركز الإسلامي في طاجيكستان — زاوية فجر 18° وعشاء 17°." else "Islamic Center of Tajikistan — 18° Fajr and 17° Isha."
        VIENNA -> if (language == Language.AR) "الهيئة الإسلامية في النمسا بفيينا — زاوية فجر 18° وعشاء 17°." else "Islamic Community of Austria, Vienna — 18° Fajr and 17° Isha."
        BELGIUM -> if (language == Language.AR) "بلجيكا — زاوية فجر 18° وعشاء 17°." else "Belgium — 18° Fajr and 17° Isha."
        SUDAN -> if (language == Language.AR) "السودان — زاوية فجر 19.5° وعشاء 17.5°." else "Sudan — 19.5° Fajr and 17.5° Isha."
        LIBYA -> if (language == Language.AR) "ليبيا — زاوية فجر 19.5° وعشاء 17.5°." else "Libya — 19.5° Fajr and 17.5° Isha."
        IRAQ -> if (language == Language.AR) "العراق — زاوية فجر 18° وعشاء 17°." else "Iraq — 18° Fajr and 17° Isha."
        LUXEMBOURG -> if (language == Language.AR) "لوكسمبورغ — زاوية فجر 18° وعشاء 17°." else "Luxembourg — 18° Fajr and 17° Isha."
        CUSTOM -> if (language == Language.AR) "طريقة مخصّصة يوفّرها المستخدم بمعاملات الشفق الخاصة به." else "A user-supplied method that uses your own twilight parameters."
    }

    companion object {
        /** Looks a method up by id, falling back to [MWL]. */
        @JvmStatic
        fun fromId(id: Int): CalculationMethod = entries.firstOrNull { it.id == id } ?: MWL

        /** Looks a method up by code, falling back to [MWL]. */
        @JvmStatic
        fun fromCode(code: String): CalculationMethod = entries.firstOrNull { it.code == code } ?: MWL
    }
}
