// Generated by islamic_kit_plus tool/generate_native_data.dart — DO NOT EDIT.
// Regenerate from the Dart package; every literal here mirrors the Dart source.

package io.github.bilalelsayed97.islamickit.domain.enums

/**
 * End-user localization (title + description) for every enum except
 * [CalculationMethod], which carries its own. Enums delegate their
 * [Localized] members here.
 */
internal object EnumStrings {
    fun title(value: AsrSchool, language: Language): String = when (value) {
        AsrSchool.STANDARD -> if (language == Language.AR) "القياسي (الشافعي والمالكي والحنبلي)" else "Standard (Shafi'i, Maliki, Hanbali)"
        AsrSchool.HANAFI -> if (language == Language.AR) "الحنفي" else "Hanafi"
    }

    fun description(value: AsrSchool, language: Language): String = when (value) {
        AsrSchool.STANDARD -> if (language == Language.AR) "يبدأ وقت العصر عندما يساوي طول ظل الشيء طوله (معامل الظل 1)." else "Asr begins when an object's shadow equals its own length (shadow factor 1)."
        AsrSchool.HANAFI -> if (language == Language.AR) "يبدأ وقت العصر عندما يبلغ طول ظل الشيء ضعف طوله (معامل الظل 2)." else "Asr begins when an object's shadow is twice its own length (shadow factor 2)."
    }

    fun title(value: MidnightMode, language: Language): String = when (value) {
        MidnightMode.STANDARD -> if (language == Language.AR) "القياسي" else "Standard"
        MidnightMode.JAFARI -> if (language == Language.AR) "الجعفري (الشيعة)" else "Jafari (Shia)"
    }

    fun description(value: MidnightMode, language: Language): String = when (value) {
        MidnightMode.STANDARD -> if (language == Language.AR) "منتصف الليل هو منتصف المدة بين الغروب وشروق اليوم التالي." else "Midnight is the midpoint between sunset and the following sunrise."
        MidnightMode.JAFARI -> if (language == Language.AR) "منتصف الليل هو منتصف المدة بين الغروب وفجر اليوم التالي." else "Midnight is the midpoint between sunset and the following Fajr."
    }

    fun title(value: HighLatitudeRule, language: Language): String = when (value) {
        HighLatitudeRule.NONE -> if (language == Language.AR) "بدون" else "None"
        HighLatitudeRule.MIDDLE_OF_NIGHT -> if (language == Language.AR) "منتصف الليل" else "Middle of Night"
        HighLatitudeRule.ONE_SEVENTH -> if (language == Language.AR) "سُبع الليل" else "One-Seventh"
        HighLatitudeRule.ANGLE_BASED -> if (language == Language.AR) "حسب الزاوية" else "Angle-Based"
    }

    fun description(value: HighLatitudeRule, language: Language): String = when (value) {
        HighLatitudeRule.NONE -> if (language == Language.AR) "لا يُطبَّق أي تعديل على المواقيت في خطوط العرض العالية." else "No high-latitude adjustment is applied to the twilight times."
        HighLatitudeRule.MIDDLE_OF_NIGHT -> if (language == Language.AR) "يُقسَّم الليل نصفين ليقيّد وقتي الفجر والعشاء عند منتصف الليل." else "The night is split in half to bound the Fajr and Isha times at its midpoint."
        HighLatitudeRule.ONE_SEVENTH -> if (language == Language.AR) "يُقسَّم الليل إلى سبعة أجزاء لضبط وقتي الفجر والعشاء." else "The night is divided into seven parts to bound the Fajr and Isha times."
        HighLatitudeRule.ANGLE_BASED -> if (language == Language.AR) "يُستخدم جزء من الليل يتناسب مع زاوية الشفق (الزاوية ÷ 60)." else "A portion of the night proportional to the twilight angle (angle / 60) is used."
    }

    fun title(value: Shafaq, language: Language): String = when (value) {
        Shafaq.GENERAL -> if (language == Language.AR) "عام" else "General"
        Shafaq.AHMER -> if (language == Language.AR) "الشفق الأحمر" else "Red Twilight"
        Shafaq.ABYAD -> if (language == Language.AR) "الشفق الأبيض" else "White Twilight"
    }

    fun description(value: Shafaq, language: Language): String = when (value) {
        Shafaq.GENERAL -> if (language == Language.AR) "الشفق العام الذي يجمع بين الحُمرة والبياض، ويُستخدم لحساب العشاء." else "General twilight, combining the red and white afterglow, used to compute Isha."
        Shafaq.AHMER -> if (language == Language.AR) "يُحسب وقت العشاء بناءً على مغيب الشفق الأحمر." else "Isha is based on the disappearance of the red twilight (shafaq al-ahmar)."
        Shafaq.ABYAD -> if (language == Language.AR) "يُحسب وقت العشاء بناءً على مغيب الشفق الأبيض." else "Isha is based on the disappearance of the white twilight (shafaq al-abyad)."
    }

    fun title(value: CalendarMethod, language: Language): String = when (value) {
        CalendarMethod.HJCOSA -> if (language == Language.AR) "الهيئة العليا للقضاء" else "High Judicial Council (KSA)"
        CalendarMethod.UAQ -> if (language == Language.AR) "أم القرى" else "Umm al-Qura"
        CalendarMethod.DIYANET -> if (language == Language.AR) "ديانت التركية" else "Diyanet (Turkey)"
        CalendarMethod.MATHEMATICAL -> if (language == Language.AR) "حسابي" else "Mathematical"
    }

    fun description(value: CalendarMethod, language: Language): String = when (value) {
        CalendarMethod.HJCOSA -> if (language == Language.AR) "تقويم أم القرى مع تعديلات الرؤية المعتمدة من الهيئة العليا للقضاء في السعودية (الإعداد الافتراضي)." else "Umm al-Qura calendar with the Saudi High Judicial Council sighting adjustments (aladhan default)."
        CalendarMethod.UAQ -> if (language == Language.AR) "تقويم أم القرى الجدولي الرسمي في المملكة العربية السعودية." else "The official Umm al-Qura tabular calendar of Saudi Arabia."
        CalendarMethod.DIYANET -> if (language == Language.AR) "التقويم الهجري الجدولي الصادر عن رئاسة الشؤون الدينية التركية (ديانت)." else "The tabular Hijri calendar published by Turkey's Diyanet İşleri Başkanlığı."
        CalendarMethod.MATHEMATICAL -> if (language == Language.AR) "تقويم هجري حسابي (جدولي) بحت يدعم تعديل الأيام." else "A purely arithmetic (tabular) Hijri calendar that supports a day adjustment."
    }

    fun title(value: TimeFormat, language: Language): String = when (value) {
        TimeFormat.H24 -> if (language == Language.AR) "24 ساعة" else "24-Hour"
        TimeFormat.H12 -> if (language == Language.AR) "12 ساعة" else "12-Hour"
        TimeFormat.H12_NO_SUFFIX -> if (language == Language.AR) "12 ساعة بدون لاحقة" else "12-Hour (No Suffix)"
        TimeFormat.FLOAT -> if (language == Language.AR) "ساعات عشرية" else "Decimal Hours"
        TimeFormat.ISO8601 -> if (language == Language.AR) "آيزو 8601" else "ISO 8601"
    }

    fun description(value: TimeFormat, language: Language): String = when (value) {
        TimeFormat.H24 -> if (language == Language.AR) "نظام 24 ساعة، مثل 03:57." else "24-hour clock, e.g. 03:57."
        TimeFormat.H12 -> if (language == Language.AR) "نظام 12 ساعة مع لاحقة ص/م، مثل 3:57 ص." else "12-hour clock with an am/pm suffix, e.g. 3:57 am."
        TimeFormat.H12_NO_SUFFIX -> if (language == Language.AR) "نظام 12 ساعة بدون لاحقة ص/م، مثل 3:57." else "12-hour clock without an am/pm suffix, e.g. 3:57."
        TimeFormat.FLOAT -> if (language == Language.AR) "ساعات عشرية خام من 0 إلى 24، مثل 3.95." else "Raw floating-point hours from 0 to 24, e.g. 3.95."
        TimeFormat.ISO8601 -> if (language == Language.AR) "طابع زمني بصيغة آيزو 8601 مع إزاحة المنطقة الزمنية، مثل 2014-04-24T03:57:00+01:00." else "ISO-8601 timestamp with a timezone offset, e.g. 2014-04-24T03:57:00+01:00."
    }

    fun title(value: Prayer, language: Language): String = when (value) {
        Prayer.IMSAK -> if (language == Language.AR) "الإمساك" else "Imsak"
        Prayer.FAJR -> if (language == Language.AR) "الفجر" else "Fajr"
        Prayer.SUNRISE -> if (language == Language.AR) "الشروق" else "Sunrise"
        Prayer.DHUHR -> if (language == Language.AR) "الظهر" else "Dhuhr"
        Prayer.ASR -> if (language == Language.AR) "العصر" else "Asr"
        Prayer.SUNSET -> if (language == Language.AR) "الغروب" else "Sunset"
        Prayer.MAGHRIB -> if (language == Language.AR) "المغرب" else "Maghrib"
        Prayer.ISHA -> if (language == Language.AR) "العشاء" else "Isha"
        Prayer.MIDNIGHT -> if (language == Language.AR) "منتصف الليل" else "Midnight"
        Prayer.FIRST_THIRD -> if (language == Language.AR) "الثلث الأول" else "First Third"
        Prayer.LAST_THIRD -> if (language == Language.AR) "الثلث الأخير" else "Last Third"
    }

    fun description(value: Prayer, language: Language): String = when (value) {
        Prayer.IMSAK -> if (language == Language.AR) "وقت الإمساك عن الطعام قبل الفجر أثناء الصيام." else "The time to stop eating before Fajr while fasting."
        Prayer.FAJR -> if (language == Language.AR) "صلاة الفجر التي تُؤدَّى قبل شروق الشمس." else "The dawn prayer, observed before sunrise."
        Prayer.SUNRISE -> if (language == Language.AR) "لحظة شروق الشمس التي تنتهي عندها فترة صلاة الفجر." else "The moment the sun rises, marking the end of the Fajr window."
        Prayer.DHUHR -> if (language == Language.AR) "صلاة الظهر التي تُؤدَّى بعد زوال الشمس عن كبد السماء." else "The noon prayer, observed just after the sun passes its zenith."
        Prayer.ASR -> if (language == Language.AR) "صلاة العصر في فترة ما بعد الظهر." else "The afternoon prayer."
        Prayer.SUNSET -> if (language == Language.AR) "لحظة غروب الشمس التي يبدأ عندها وقت المغرب." else "The moment the sun sets, coinciding with the start of Maghrib."
        Prayer.MAGHRIB -> if (language == Language.AR) "صلاة المغرب التي تُؤدَّى بعد غروب الشمس مباشرة." else "The sunset prayer, observed just after the sun has set."
        Prayer.ISHA -> if (language == Language.AR) "صلاة العشاء التي تُؤدَّى بعد غياب الشفق." else "The night prayer, observed after twilight has disappeared."
        Prayer.MIDNIGHT -> if (language == Language.AR) "منتصف الليل الشرعي بين الغروب والفجر." else "The midpoint of the Islamic night."
        Prayer.FIRST_THIRD -> if (language == Language.AR) "نهاية الثلث الأول من الليل." else "The end of the first third of the night."
        Prayer.LAST_THIRD -> if (language == Language.AR) "بداية الثلث الأخير من الليل، وهو وقت مستحب لقيام الليل." else "The start of the last third of the night, favored for night prayer."
    }

    fun title(value: Language, language: Language): String = when (value) {
        Language.EN -> if (language == Language.AR) "الإنجليزية" else "English"
        Language.AR -> if (language == Language.AR) "العربية" else "Arabic"
    }

    fun description(value: Language, language: Language): String = when (value) {
        Language.EN -> if (language == Language.AR) "عرض أسماء الصلوات والأشهر وأيام الأسبوع باللغة الإنجليزية." else "Display prayer, month and weekday names in English."
        Language.AR -> if (language == Language.AR) "عرض أسماء الصلوات والأشهر وأيام الأسبوع باللغة العربية." else "Display prayer, month and weekday names in Arabic."
    }
}
