// Generated by islamic_kit_plus tool/generate_native_data.dart — DO NOT EDIT.
// Regenerate from the Dart package; every literal here mirrors the Dart source.

package io.github.bilalelsayed97.islamickit.infrastructure.calendar.data

/** Islamic holidays keyed by Hijri month, then day. */
internal object HijriHolidays {
    @JvmField
    val byMonth: Map<Int, Map<Int, List<String>>> = mapOf(
        1 to mapOf(
            1 to listOf("Birth of Khas Muhammad ash-Shirwani ق"),
            9 to listOf("Urs of Sayyidina Qāsim ibn Muḥammad ibn Abī Bakr ق"),
            10 to listOf("Ashura", "Urs of Shaykh Shamsuddin Habīb Allah ق", "Urs of Shaykh Abū al‑Hassan al‑Kharqāni ق", "Birth of Imam Rābbani Ahmad Al-Fāruqi As-Sirhindi ق"),
            14 to listOf("Birth of Khwaja Bahauddin Shah Naqshband ق"),
            16 to listOf("Birth of Shaykh Jamaluddin al-Ghumuqi al-Husayni ق"),
            17 to listOf("Urs of Shaykh Muhammad Effendi al‑Yaraghi ق"),
            19 to listOf("Urs of Shaykh Darwish Muhammad ق"),
            25 to listOf("Urs of Sayyidina Ali ibn Zayn al-Abidin ق"),
        ),
        2 to mapOf(
            1 to listOf("End of the holy months"),
            5 to listOf("Urs of Shaykh Yaʿqub al-Charkhi (ق)"),
            12 to listOf("Urs of Shaykh Abdullah Dahlawi (ق)"),
            17 to listOf("Urs of Imam Rabbani Ahmad al-Faruqi as-Sirhindi (ق)"),
            28 to listOf("Martyrdom of Sayyidina al-Hassan al-Mujtaba (ر)"),
        ),
        3 to mapOf(
            3 to listOf("Urs of Shaykh Bahaʾuddin Shah Naqshband ق"),
            6 to listOf("Birth of Mawlāna Jalāluddīn Rūmi ق"),
            9 to listOf("Urs of Shaykh Muhammad al-Masūm ق"),
            12 to listOf("Mawlid (Birth) al-Nabi ﷺ", "Veiling of the Prophet Muhammad ﷺ", "Birth of Mawlana Shaykh Abdullāh al Dāghestāni ق", "Urs of Shaykh Abu Yāqub Yūsuf al-Hamadāni ق", "Urs of Shaykh Abdul Khāliq al-Ghujdawāni ق", "Urs of Mawlāna Ubaydullaāh Ahrār ق", "Urs of Shaykh Muhammad az-Zāhid ق"),
            17 to listOf("Urs of Shaykh Mahmūd al-Anjir al-Faghnāwi ق", "Urs of Shaykh Abu Ahmad as-Sughūri ق"),
            18 to listOf("Urs of Shaykh Adnān Kabbāni ق"),
        ),
        4 to mapOf(
            11 to listOf("Urs of Shaykh Abdul Qadir Jilāni ق"),
            14 to listOf("Urs of Imām Abu Hamīd al-Ghazzāli ق"),
            22 to listOf("Urs of Shaykh Muhiyuddīn Ibn al-‘Arabi ق"),
        ),
        5 to mapOf(
            27 to listOf("Urs of Shaykh Sharafuddīn ad-Daghestāni ق"),
        ),
        6 to mapOf(
            3 to listOf("Urs of Mawlānā Shaykh Hishām Kabbāni ق"),
            10 to listOf("Urs of Muhammad Bābā as-Samasi ق"),
            14 to listOf("Urs of Muhammad Bāqi Billāh  ق"),
        ),
        7 to mapOf(
            1 to listOf("Beginning of the holy months"),
            6 to listOf("Urs of Hadhrat Shaykh Moīn al-Dīn Chishti (ق)"),
            8 to listOf("Urs of Mawlāna Shaykh Nāzim al-Haqqāni (ق)"),
            13 to listOf("Birth of Sayyidina `Ali ibn Abi Talib (ر)"),
            15 to listOf("Urs of Sayyidina Jāfar as-Sādiq (ق)", "Urs of Zaynab bint Ali (ر)"),
            27 to listOf("Lailat-ul-Miraj"),
        ),
        8 to mapOf(
            3 to listOf("Birth of Sayyidina Husayn ibn `Ali (ر)"),
            4 to listOf("Birth of Sayyidina Abbas ibn `Ali (ر)"),
            5 to listOf("Birth of Sayyidina `Ali ibn Husayn (ر)", "Urs of Imam Shamil al-Daghestani (ق)"),
            7 to listOf("Birth of Sayyidina Qasim ibn Hasan (ر)"),
            11 to listOf("Birth of Sayyidina Ali Akbar ibn Husayn (ر)"),
            15 to listOf("Lailat-ul-Bara'at", "Urs of Sayyidina Abu Yazid al-Bistami (ق)"),
            22 to listOf("Urs of Muhammad Usman Damani (ق)"),
        ),
        9 to mapOf(
            1 to listOf("1st Day of Ramadan"),
            21 to listOf("Lailat-ul-Qadr"),
            23 to listOf("Lailat-ul-Qadr"),
            25 to listOf("Lailat-ul-Qadr"),
            27 to listOf("Lailat-ul-Qadr"),
            29 to listOf("Lailat-ul-Qadr"),
        ),
        10 to mapOf(
            1 to listOf("Eid-ul-Fitr"),
            3 to listOf("Urs of Hajjah Amina Ādil ق", "Birth of Imam Bukhārī (ر)"),
        ),
        11 to mapOf(
            1 to listOf("Treaty of Hudaybiyya"),
            2 to listOf("Birth of Muhammad Effendi al-Yaraghi (ق) "),
            3 to listOf("Birth of Sharafuddin ad-Daghestani (ق)"),
            7 to listOf("Birth of Ismail Muhammad ash-Shirwani (ق)"),
            13 to listOf("Urs of Khalid al-Baghdadi (ق)"),
            18 to listOf("Urs of Ali ar-Ramitani (ق)"),
        ),
        12 to mapOf(
            8 to listOf("Hajj"),
            9 to listOf("Hajj", "Arafa"),
            10 to listOf("Eid-ul-Adha", "Hajj", "Urs Ismail Muhammad ash-Shirwani ق"),
            11 to listOf("Hajj", "Urs of Uthman ibn Affan (3rd Caliph) (ر)"),
            12 to listOf("Hajj"),
            13 to listOf("Hajj"),
            19 to listOf("First time Adhan was called in 622 AD"),
        ),
    )
}
