package io.github.bilalelsayed97.islamickit.conformance

import io.github.bilalelsayed97.islamickit.domain.enums.AsrSchool
import io.github.bilalelsayed97.islamickit.domain.enums.CalculationMethod
import io.github.bilalelsayed97.islamickit.domain.enums.CalendarMethod
import io.github.bilalelsayed97.islamickit.domain.enums.HighLatitudeRule
import io.github.bilalelsayed97.islamickit.domain.enums.MidnightMode
import io.github.bilalelsayed97.islamickit.domain.enums.Prayer
import io.github.bilalelsayed97.islamickit.domain.enums.Shafaq
import io.github.bilalelsayed97.islamickit.domain.models.HijriDate
import io.github.bilalelsayed97.islamickit.domain.valueobjects.CalculationParameters
import io.github.bilalelsayed97.islamickit.domain.valueobjects.Coordinates
import io.github.bilalelsayed97.islamickit.domain.valueobjects.MethodAdjustments
import io.github.bilalelsayed97.islamickit.domain.valueobjects.MethodParams
import io.github.bilalelsayed97.islamickit.domain.valueobjects.Tune
import io.github.bilalelsayed97.islamickit.time.CivilDate
import io.github.bilalelsayed97.islamickit.time.CivilDateTime
import io.github.bilalelsayed97.islamickit.time.UtcOffset
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.util.concurrent.ConcurrentHashMap

/**
 * Loads the conformance fixtures generated by the Dart package
 * (`tool/conformance/generate.dart`) from the `conformance/` test resources,
 * and rebuilds the library's input types from the JSON the generator wrote.
 *
 * Shared by the `:core` and `:geocoding` test suites.
 */
object Fixtures {
    private val cache = ConcurrentHashMap<String, JsonElement>()

    /** Parses `conformance/<name>` from the test classpath (cached per JVM). */
    fun load(name: String): JsonElement = cache.getOrPut(name) {
        val stream = Fixtures::class.java.classLoader.getResourceAsStream("conformance/$name")
            ?: throw IllegalStateException("Fixture conformance/$name is not on the test classpath")
        val text = stream.use { it.readBytes().toString(Charsets.UTF_8) }
        Json.parseToJsonElement(text)
    }

    /** The `cases` array of a fixture file, each case as an object. */
    fun cases(name: String): List<JsonObject> = load(name).jsonObject.getValue("cases").jsonArray.map { it.jsonObject }

    /** `yyyy-mm-dd` → [CivilDate]. */
    fun date(text: String): CivilDate {
        val (y, m, d) = text.split('-').map { it.toInt() }
        return CivilDate(y, m, d)
    }

    /** `yyyy-mm-ddThh:mm:ss` → [CivilDateTime]. */
    fun dateTime(text: String): CivilDateTime {
        val (datePart, timePart) = text.split('T')
        val (h, mi, s) = timePart.split(':').map { it.toInt() }
        return CivilDateTime(date(datePart), h, mi, s)
    }

    /** `dd-mm-yyyy` (the fixtures' Hijri form) → `(year, month, day)`. */
    fun hijriParts(text: String): Triple<Int, Int, Int> {
        val (d, m, y) = text.split('-').map { it.toInt() }
        return Triple(y, m, d)
    }

    /** Rebuilds the [CalculationParameters] the generator serialised with `_paramsJson`. */
    fun params(json: JsonObject): CalculationParameters = CalculationParameters(
        method = methodByCode(json.str("method")),
        customMethod = json.objOrNull("customMethod")?.let(::methodParams),
        school = AsrSchool.entries.first { it.metaValue == json.str("school") },
        asrShadowFactor = json.doubleOrNull("asrShadowFactor"),
        midnightMode = json.strOrNull("midnightMode")?.let { v -> MidnightMode.entries.first { it.metaValue == v } },
        highLatitudeRule = HighLatitudeRule.entries.first { it.metaValue == json.str("highLatitudeRule") },
        utcOffset = UtcOffset(json.int("utcOffsetSeconds")),
        elevation = json.double("elevation"),
        shafaq = Shafaq.entries.first { it.code == json.str("shafaq") },
        tune = Tune.fromCsv(json.str("tune")),
        imsakMinutes = json.int("imsakMinutes"),
        dhuhrMinutes = json.int("dhuhrMinutes"),
        calendarMethod = calendarMethodByCode(json.str("calendarMethod")),
        timezoneName = json.strOrNull("timezoneName"),
    )

    /** Rebuilds a [MethodParams] from the generator's `_methodParamsJson`. */
    fun methodParams(json: JsonObject): MethodParams {
        val adj = json.getValue("adjustments").jsonObject
        val loc = json.objOrNull("location")
        return MethodParams(
            fajrAngle = json.double("fajrAngle"),
            ishaAngle = json.doubleOrNull("ishaAngle"),
            ishaMinutesAfterMaghrib = json.intOrNull("ishaMinutesAfterMaghrib"),
            ramadanIshaMinutesAfterMaghrib = json.intOrNull("ramadanIshaMinutesAfterMaghrib"),
            maghribAngle = json.doubleOrNull("maghribAngle"),
            maghribMinutesAfterSunset = json.intOrNull("maghribMinutesAfterSunset"),
            adjustments = MethodAdjustments(
                fajr = adj.int("fajr"),
                sunrise = adj.int("sunrise"),
                dhuhr = adj.int("dhuhr"),
                asr = adj.int("asr"),
                maghrib = adj.int("maghrib"),
                isha = adj.int("isha"),
            ),
            midnightMode = json.strOrNull("midnightMode")?.let { v -> MidnightMode.entries.first { it.metaValue == v } },
            location = loc?.let { Coordinates(it.double("lat"), it.double("lng")) },
        )
    }

    /** The generator's `_paramsJson` shape, for comparing parameters the library derived itself. */
    fun paramsJson(p: CalculationParameters): Map<String, Any?> = linkedMapOf(
        "method" to p.method.code,
        "customMethod" to p.customMethod?.let(::methodParamsJson),
        "school" to p.school.metaValue,
        "asrShadowFactor" to p.asrShadowFactor,
        "midnightMode" to p.midnightMode?.metaValue,
        "highLatitudeRule" to p.highLatitudeRule.metaValue,
        "utcOffsetSeconds" to p.utcOffset.totalSeconds,
        "elevation" to p.elevation,
        "shafaq" to p.shafaq.code,
        "tune" to p.tune.toCsv(),
        "imsakMinutes" to p.imsakMinutes,
        "dhuhrMinutes" to p.dhuhrMinutes,
        "calendarMethod" to p.calendarMethod.code,
        "timezoneName" to p.timezoneName,
    )

    /** The generator's `_methodParamsJson` shape. */
    fun methodParamsJson(p: MethodParams): Map<String, Any?> = linkedMapOf(
        "fajrAngle" to p.fajrAngle,
        "ishaAngle" to p.ishaAngle,
        "ishaMinutesAfterMaghrib" to p.ishaMinutesAfterMaghrib,
        "ramadanIshaMinutesAfterMaghrib" to p.ramadanIshaMinutesAfterMaghrib,
        "maghribAngle" to p.maghribAngle,
        "maghribMinutesAfterSunset" to p.maghribMinutesAfterSunset,
        "adjustments" to linkedMapOf(
            "fajr" to p.adjustments.fajr,
            "sunrise" to p.adjustments.sunrise,
            "dhuhr" to p.adjustments.dhuhr,
            "asr" to p.adjustments.asr,
            "maghrib" to p.adjustments.maghrib,
            "isha" to p.adjustments.isha,
        ),
        "midnightMode" to p.midnightMode?.metaValue,
        "location" to p.location?.let { linkedMapOf("lat" to it.latitude, "lng" to it.longitude) },
    )

    /** The generator's `_hijriJson` shape, in its key order. */
    fun hijriJson(h: HijriDate): Map<String, Any?> = linkedMapOf(
        "hijri" to h.formatted,
        "day" to h.day,
        "month" to h.month,
        "year" to h.year,
        "monthLength" to h.monthLength,
        "weekdayEn" to h.weekdayEn,
        "weekdayAr" to h.weekdayAr,
        "monthEn" to h.monthEn,
        "monthAr" to h.monthAr,
        "method" to h.method.code,
        "holidays" to h.holidays,
    )

    /** The generator's `_rawJson` shape: every prayer key, in [Prayer] order, to its raw hours. */
    fun rawJson(raw: Map<Prayer, Double?>): Map<String, Any?> {
        val out = LinkedHashMap<String, Any?>()
        for (p in Prayer.entries) out[p.key] = raw[p]
        return out
    }

    /** Strict lookup by aladhan code (no fallback, unlike `CalculationMethod.fromCode`). */
    fun methodByCode(code: String): CalculationMethod =
        CalculationMethod.entries.firstOrNull { it.code == code }
            ?: throw IllegalArgumentException("Unknown method code in fixture: $code")

    /** Strict lookup by code (no fallback, unlike `CalendarMethod.fromCode`). */
    fun calendarMethodByCode(code: String): CalendarMethod =
        CalendarMethod.entries.firstOrNull { it.code == code }
            ?: throw IllegalArgumentException("Unknown calendar method code in fixture: $code")
}

// --- JsonObject accessors --------------------------------------------------

/** The string at [key]; fails when absent or `null`. */
fun JsonObject.str(key: String): String = strOrNull(key) ?: throw IllegalStateException("Missing string \"$key\"")

/** The string at [key], or `null` when absent or JSON `null`. */
fun JsonObject.strOrNull(key: String): String? {
    val v = this[key] ?: return null
    if (v is JsonNull) return null
    val p = v.jsonPrimitive
    check(p.isString) { "\"$key\" is not a string: $p" }
    return p.content
}

/** The integer at [key]; fails when absent or `null`. */
fun JsonObject.int(key: String): Int = intOrNull(key) ?: throw IllegalStateException("Missing int \"$key\"")

/** The integer at [key], or `null` when absent or JSON `null`. */
fun JsonObject.intOrNull(key: String): Int? {
    val v = this[key] ?: return null
    if (v is JsonNull) return null
    return v.jsonPrimitive.content.toInt()
}

/** The number at [key] as a `Double`; fails when absent or `null`. */
fun JsonObject.double(key: String): Double = doubleOrNull(key) ?: throw IllegalStateException("Missing double \"$key\"")

/** The number at [key] as a `Double`, or `null` when absent or JSON `null`. */
fun JsonObject.doubleOrNull(key: String): Double? {
    val v = this[key] ?: return null
    if (v is JsonNull) return null
    return v.jsonPrimitive.content.toDouble()
}

/** The boolean at [key]. */
fun JsonObject.bool(key: String): Boolean = this.getValue(key).jsonPrimitive.content.toBooleanStrict()

/** The object at [key], or `null` when absent or JSON `null`. */
fun JsonObject.objOrNull(key: String): JsonObject? {
    val v = this[key] ?: return null
    return if (v is JsonNull) null else v.jsonObject
}

/** The object at [key]. */
fun JsonObject.obj(key: String): JsonObject = this.getValue(key).jsonObject

/** The array at [key]. */
fun JsonObject.arr(key: String): JsonArray = this.getValue(key).jsonArray

/** The string value of a primitive element. */
val JsonElement.string: String
    get() = jsonPrimitive.content

/** `true` when the element is JSON `null`. */
val JsonElement.isNull: Boolean
    get() = this is JsonNull
