// Generated by islamic_kit_plus tool/generate_native_data.dart — DO NOT EDIT.
// Regenerate from the Dart package; every literal here mirrors the Dart source.

package io.github.bilalelsayed97.islamickit.infrastructure.localization

/** A localized (English + Arabic) name pair. */
data class LocalizedName(val en: String, val ar: String)

/**
 * Static English/Arabic name tables for Gregorian and Hijri calendars.
 *
 * Weekdays are keyed by ISO weekday number (Mon = 1 … Sun = 7).
 */
object Localizer {
    /** Hijri months 1..12. */
    @JvmField
    val islamicMonths: Map<Int, LocalizedName> = linkedMapOf(
        1 to LocalizedName("Muharram", "مُحَرَّم"),
        2 to LocalizedName("Safar", "صَفَر"),
        3 to LocalizedName("Rabi al-awwal", "رَبيع الأوّل"),
        4 to LocalizedName("Rabi al-thani", "رَبيع الثاني"),
        5 to LocalizedName("Jumadi al-awal", "جُمادى الأول"),
        6 to LocalizedName("Jumadi al-akhir", "جُمادى الآخر"),
        7 to LocalizedName("Rajab", "رَجَب"),
        8 to LocalizedName("Sha'ban", "شَعْبان"),
        9 to LocalizedName("Ramadan", "رَمَضان"),
        10 to LocalizedName("Shawwal", "شَوّال"),
        11 to LocalizedName("Dhu al-Qa'dah", "ذوالقعدة"),
        12 to LocalizedName("Dhu al-Hijjah", "ذوالحجة"),
    )

    /** Hijri weekday names keyed by ISO weekday (Mon = 1 … Sun = 7). */
    @JvmField
    val hijriWeekdays: Map<Int, LocalizedName> = linkedMapOf(
        1 to LocalizedName("Monday", "الاثنين"),
        2 to LocalizedName("Tuesday", "الثلاثاء"),
        3 to LocalizedName("Wednesday", "الاربعاء"),
        4 to LocalizedName("Thursday", "الخميس"),
        5 to LocalizedName("Friday", "الجمعة"),
        6 to LocalizedName("Saturday", "السبت"),
        7 to LocalizedName("Sunday", "الاحد"),
    )

    /** Gregorian months 1..12. */
    @JvmField
    val gregorianMonths: Map<Int, LocalizedName> = linkedMapOf(
        1 to LocalizedName("January", "يناير"),
        2 to LocalizedName("February", "فبراير"),
        3 to LocalizedName("March", "مارس"),
        4 to LocalizedName("April", "أبريل"),
        5 to LocalizedName("May", "مايو"),
        6 to LocalizedName("June", "يونيو"),
        7 to LocalizedName("July", "يوليو"),
        8 to LocalizedName("August", "أغسطس"),
        9 to LocalizedName("September", "سبتمبر"),
        10 to LocalizedName("October", "أكتوبر"),
        11 to LocalizedName("November", "نوفمبر"),
        12 to LocalizedName("December", "ديسمبر"),
    )

    /** Gregorian weekday names keyed by ISO weekday (Mon = 1 … Sun = 7). */
    @JvmField
    val gregorianWeekdays: Map<Int, LocalizedName> = linkedMapOf(
        1 to LocalizedName("Monday", "الإثنين"),
        2 to LocalizedName("Tuesday", "الثلاثاء"),
        3 to LocalizedName("Wednesday", "الأربعاء"),
        4 to LocalizedName("Thursday", "الخميس"),
        5 to LocalizedName("Friday", "الجمعة"),
        6 to LocalizedName("Saturday", "السبت"),
        7 to LocalizedName("Sunday", "الأحد"),
    )

    /** English three-letter month abbreviations, index 0 = January. */
    @JvmField
    val monthAbbrEn: List<String> = listOf("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

    /** Hijri weekday name for an ISO weekday (Mon = 1 … Sun = 7). */
    @JvmStatic
    fun hijriWeekday(isoWeekday: Int): LocalizedName = hijriWeekdays.getValue(isoWeekday)

    /** Gregorian weekday name for an ISO weekday (Mon = 1 … Sun = 7). */
    @JvmStatic
    fun gregorianWeekday(isoWeekday: Int): LocalizedName = gregorianWeekdays.getValue(isoWeekday)
}
